name: Deploy to Droplet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you add a build step later, put it here
      # - run: npm ci && npm run build

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Upload files with rsync
        run: |
          rsync -avz --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/"
